// AUTH 관련 에러 정의
const NO_BMCOOKIE_ERROR_MSG = '헤더에 설정된 COOKIE가 없습니다.';
const NO_BMCOOKIE_ERROR_TYPE = 'ERR_000';
const NO_SESSION_INFOR_ERROR_MSG = '로그인 되어있지 않습니다.';
const NO_SESSION_INFOR_ERROR_TYPE = 'ERR_001';
const UNVALID_INFO_ERROR_MSG = '로그인된 아이디와 COOKIE가 다릅니다.';
const UNVALID_INFO_ERROR_TYPE = 'ERR_002';

// 내부 문제 관련 정의
const INTERNAL_SERVER_ERROR_MSG = '서버 에러';
const INTERNAL_SERVER_ERROR_TYPE = 'ERR_100';
const DB_QUERY_ERROR_MSG = 'DB 처리중에 문제가 발생했습니다.';
const DB_QUERY_ERROR_TYPE = 'ERR_101';

exports.module = {
  NO_BMCOOKIE_ERROR_MSG,
  NO_BMCOOKIE_ERROR_TYPE,
  NO_SESSION_INFOR_ERROR_MSG,
  NO_SESSION_INFOR_ERROR_TYPE,
  UNVALID_INFO_ERROR_MSG,
  UNVALID_INFO_ERROR_TYPE,
  INTERNAL_SERVER_ERROR_MSG,
  INTERNAL_SERVER_ERROR_TYPE,
  DB_QUERY_ERROR_MSG,
  DB_QUERY_ERROR_TYPE,
};
